groq:
  api_key: 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

database:
  db_uri: postgresql://cenomi_owner:npg_C2FBJbKqSY3H@ep-sparkling-sun-a1ye4tdb-pooler.ap-southeast-1.aws.neon.tech/cenomi?sslmode=require

chromadb:
  persist_directory: "D:/cenomi_malls_chatbot/data/chroma"

llm:
  model_name: "gemini-2.0-flash"
  api_key: AIzaSyCsm_mqOBKXeu72mdRAzQUqLptlWjMiJ6o
